/**
 * Page main js functionality
 * @param
 * @return
 **/
var main = function() {

  //Call fizzBuzz on button click
  $('.show-result').on('click', function() {

    var $p = $('<p>');

    $('.result').html('');
    var inputText = $('input.range').val();

    //gerente an array by spliting the input value
    var rangeArray = inputText.split(',');
    var invalidInput = false;

    //Validate input value
    if (rangeArray.length != 2) { //check if array length is 2
      invalidInput = true;
    } else if (!$.isNumeric(rangeArray[0]) || !$.isNumeric(rangeArray[1])) { //check the items in the array generated by spliting text are numbers
      invalidInput = true;
    } else if (rangeArray[1] <= rangeArray[0]) { //check the last item of array is larger then the first
      invalidInput = true;
    }

    if (invalidInput) {
      alert("Input text is not valid. The correct format is: n1,n2 - where n1 and n2 are number, and n2 is larger than n1");
    } else {
      fizzBuzz(rangeArray[0], rangeArray[1]);
    }

  });

  //Trigger button click on enter press
  $("input.range").on("keypress", function(event) {
    if (event.keyCode === 13) {
      $('.show-result')[0].click();
    }
  });

}

/**
 * Iterates in the given array and prints Fizz, Buzz or FizzBuzz
 * when the current array value is a number multiple of 3,5, or 3 & 5 respectivelly
 * @param rangeStart - the start of the range of integers i.e. 1
 * @param rangeEnd - the start of the range of integers i.e. 100
 * @return $p - paragraph 'n: Fizz','n: Buzz' or 'n: FizzBuzz', where n is a number within the range
 **/
var fizzBuzz = function(rangeStart, rangeEnd) {

  //Validate ranges - Check if array's last number in the array
  if (rangeEnd <= rangeStart) {
    return 'Max range shoulr be a number larger than the min range';
  }

  for (i = rangeStart; i <= rangeEnd; i++) {
    var $p = $('<p>');
    if (i % 3 == 0) {
      if (i % 5 != 0) {
        $p.text(i + ": Fizz");
      } else {
        $p.text(i + ":FizzBuzz");
      }
    } else if (i % 5 == 0) {
      $p.text(i + ":Buzz");
    }
    $(".result").append($p);
  }

}

//Call main on document ready
$(document).ready(main);
